-- ═══════════════════════════════════════════════════════════════════════════
--  SMART EDU — Static reference data
--
--  Lookup rows the application logic depends on: the permission catalogue,
--  role→permission defaults and institution settings. Safe to re-run — every
--  statement is idempotent.
--
--  Demo *content* (users, classes, attendance, marks…) is generated by
--  `database/seed.js`, which needs bcrypt hashing and randomised academic
--  history that raw SQL cannot express cleanly. Run `npm run db:seed`.
-- ═══════════════════════════════════════════════════════════════════════════

-- ───────────────────────── PERMISSION CATALOGUE ───────────────────────────

INSERT INTO permissions (code, label, category, description) VALUES
  ('view_students',      'View students',       'students',   'Read student records and profiles'),
  ('edit_students',      'Edit students',       'students',   'Create and update student records'),
  ('delete_students',    'Delete students',     'students',   'Remove student records'),
  ('view_teachers',      'View teachers',       'staff',      'Read teacher records'),
  ('view_parents',       'View parents',        'people',     'Read parent records'),
  ('view_attendance',    'View attendance',     'attendance', 'Read attendance registers'),
  ('edit_attendance',    'Edit attendance',     'attendance', 'Mark and amend attendance'),
  ('view_marks',         'View marks',          'academics',  'Read assessment marks'),
  ('edit_marks',         'Edit marks',          'academics',  'Enter and amend marks'),
  ('publish_marks',      'Publish marks',       'academics',  'Release marks to students and parents'),
  ('manage_assignments', 'Manage assignments',  'academics',  'Create, edit and grade assignments'),
  ('manage_users',       'Manage users',        'admin',      'Create, disable and delete user accounts'),
  ('manage_classes',     'Manage classes',      'admin',      'Create and configure classes'),
  ('manage_subjects',    'Manage subjects',     'admin',      'Create and configure subjects'),
  ('manage_departments', 'Manage departments',  'admin',      'Create and configure departments'),
  ('manage_timetable',   'Manage timetable',    'admin',      'Build and amend the timetable'),
  ('manage_notices',     'Manage notices',      'engagement', 'Publish and withdraw notices'),
  ('manage_complaints',  'Manage complaints',   'engagement', 'Triage and resolve complaints'),
  ('manage_leave',       'Manage leave',        'engagement', 'Approve or reject leave applications'),
  ('manage_fees',        'Manage fees',         'finance',    'Configure fee structures and records'),
  ('manage_ptm',         'Manage PTM',          'engagement', 'Publish availability and manage meetings'),
  ('view_reports',       'View reports',        'insights',   'Generate and read reports'),
  ('view_analytics',     'View analytics',      'insights',   'Read institutional analytics'),
  ('view_audit_logs',    'View audit logs',     'admin',      'Inspect the audit trail'),
  ('manage_permissions', 'Manage permissions',  'admin',      'Grant and revoke permissions'),
  ('manage_settings',    'Manage settings',     'admin',      'Change institution-wide settings'),
  ('use_ai_tools',       'Use AI tools',        'ai',         'Access AI assistants and generators')
ON CONFLICT (code) DO UPDATE
  SET label = EXCLUDED.label,
      category = EXCLUDED.category,
      description = EXCLUDED.description;

-- ─────────────────────── ROLE DEFAULT PERMISSIONS ─────────────────────────
-- These are the *baseline* for a role. Per-user rows in `user_permissions`
-- can grant or revoke on top. Role checks always run first — a permission
-- never widens access beyond what the role's route guard already allows.

-- Admin: everything.
INSERT INTO role_permissions (role, permission_id)
SELECT 'admin', id FROM permissions
ON CONFLICT DO NOTHING;

-- Teacher: their classroom, plus insight and AI tooling.
INSERT INTO role_permissions (role, permission_id)
SELECT 'teacher', id FROM permissions WHERE code IN (
  'view_students', 'view_attendance', 'edit_attendance',
  'view_marks', 'edit_marks', 'publish_marks',
  'manage_assignments', 'manage_notices', 'manage_ptm',
  -- Class teachers are the first reviewer for their students' leave requests.
  'manage_leave',
  'view_reports', 'view_analytics', 'use_ai_tools'
)
ON CONFLICT DO NOTHING;

-- Student: read-only over their own record (ownership is enforced separately).
INSERT INTO role_permissions (role, permission_id)
SELECT 'student', id FROM permissions WHERE code IN (
  'view_attendance', 'view_marks', 'use_ai_tools'
)
ON CONFLICT DO NOTHING;

-- Parent: read-only over linked children, further narrowed by student privacy.
INSERT INTO role_permissions (role, permission_id)
SELECT 'parent', id FROM permissions WHERE code IN (
  'view_attendance', 'view_marks', 'use_ai_tools'
)
ON CONFLICT DO NOTHING;

-- ──────────────────────── INSTITUTION SETTINGS ────────────────────────────

INSERT INTO settings (key, value, description) VALUES
  ('institution_name',
   '"Smart Edu Institute of Technology"'::jsonb,
   'Display name used across the app'),
  ('academic_year',
   '"2025-26"'::jsonb,
   'Current academic year'),
  ('attendance_warning_threshold',
   '75'::jsonb,
   'Attendance percentage below which a student is flagged'),
  ('grading_scale',
   '[{"grade":"O","min":90,"point":10},{"grade":"A+","min":80,"point":9},{"grade":"A","min":70,"point":8},{"grade":"B+","min":60,"point":7},{"grade":"B","min":50,"point":6},{"grade":"C","min":40,"point":5},{"grade":"F","min":0,"point":0}]'::jsonb,
   'Percentage to grade/grade-point mapping used for CGPA'),
  ('risk_weights',
   '{"attendance":0.4,"performance":0.4,"assignments":0.2}'::jsonb,
   'Weights combined into the academic risk indicator'),
  ('allow_public_registration',
   'true'::jsonb,
   'Whether students and parents may self-register'),
  ('pagination_default',
   '20'::jsonb,
   'Default page size for paginated endpoints')
ON CONFLICT (key) DO NOTHING;
